version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./uploads:/app/wwwroot/uploads
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - APP_DB_CONNECTION_STRING=server=${MYSQL_SERVER};port=${MYSQL_PORT};user=${MYSQL_USER};password=${MYSQL_PASSWORD};database=${MYSQL_DATABASE}
    restart: unless-stopped
    networks:
      - app-network
    depends_on:
      - db
  db:
    image: mysql:8.0
    restart: always
    env_file:
      - .env
    environment:
      MYSQL_ROOT_PASSWORD: '${MYSQL_ROOT_PASSWORD}'
      MYSQL_DATABASE: '${MYSQL_DATABASE}'
      MYSQL_USER: '${MYSQL_USER}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    ports:
      - "3307:3306" # Use 3306:3306 if not busy by local MySQL
networks:
  app-network:
    driver: bridge

volumes:
  mysql-data: